import Navbar from './Navbar';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="winter">
      <body className="inter.className">
        <Navbar />
        <main className="p-5">{children}</main>
      </body>
    </html>
  );
}
